#!/usr/bin/env python3
import string, yaml, json, sys, os

in_dir = sys.argv[1]

data = sys.stdin.read()

for name in ("user", "host"):
    with open("{}/json/data_%s.yml".format(in_dir) % name, "r") as schema:
        json_data = json.dumps(yaml.safe_load(schema), indent=4)
        assert "$$" not in json_data
        data = data.replace("{data_%s}" % name, json_data)

sys.stdout.write(data)
